server:
  port: 8082

spring:
  application:
    name: authentication

  datasource:
    url: jdbc:mariadb://localhost:3306/user_db
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret: "5f6f62d8fb943c1eb48b5a4f7f6349e7643b25e8b6be88b9d7a09c77836dbd70"
    expirationMs: 86400000  # Token expiration in milliseconds (1 day)


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    layout: StandaloneLayout
    display-request-duration: true
