server:
  port: 8083

spring:
  application:
    name: studentservice

  datasource:
    url: jdbc:mariadb://localhost:3306/student_db
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
