server:
  port: 8083

spring:
  application:
    name: studentservice

  datasource:
    url: jdbc:mariadb://localhost:3306/student_db
    username: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    jwt:
      secret: ${JWT_SECRET_KEY}  # Ensure the same secret key used in Authentication Service
      expirationMs: 86400000  # Adjust token expiration if needed (1 day here)

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

  instance: localhost

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
