server:
  port: 8081

spring:
  application:
    name: configuration

  datasource:
    url: jdbc:mariadb://localhost:3306/schoolmanagement_db
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

