server:
  port: 8761  # Default Eureka port

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

